# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  dav1d = {
    pname = "dav1d";
    version = "7576cd572f3ab5f6543a70dcc606e131110dbcd8";
    src = fetchgit {
      url = "https://code.videolan.org/videolan/dav1d";
      rev = "7576cd572f3ab5f6543a70dcc606e131110dbcd8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-1GXlFKqrkhGCgatgCXXs8SNX4FAdRTm9bZ3sVmcK6KU=";
    };
  };
  fuzzel = {
    pname = "fuzzel";
    version = "db2ce5a1ab51edc9d4f7920aa9f3abbd90e1b39b";
    src = fetchgit {
      url = "https://codeberg.org/dnkl/fuzzel";
      rev = "db2ce5a1ab51edc9d4f7920aa9f3abbd90e1b39b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-RhCHQTIgTg3pTpjbwZt4NrnsxEqB4Vab2A58ZM0DztA=";
    };
  };
  libplacebo = {
    pname = "libplacebo";
    version = "24c30bf91a3389fd381d5949bcc27319233eea6f";
    src = fetchgit {
      url = "https://code.videolan.org/videolan/libplacebo/";
      rev = "24c30bf91a3389fd381d5949bcc27319233eea6f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-yb8f0CsOQM0KjiS+Y6QyXXoHQtGSZNxvS2r0ajV0cT4=";
    };
  };
  mpv = {
    pname = "mpv";
    version = "c4c7b07acfa58166f47136aca8187fb7e175b79e";
    src = fetchFromGitHub {
      owner = "mpv-player";
      repo = "mpv";
      rev = "c4c7b07acfa58166f47136aca8187fb7e175b79e";
      fetchSubmodules = false;
      sha256 = "sha256-fRLAP7Z5IN2aUkmLEbyXK756sSYP6w+NWfZoevCDIeE=";
    };
  };
  spellsitter = {
    pname = "spellsitter";
    version = "430a25393abbf482bddf03c224cd5b8eeb27b5e1";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "spellsitter.nvim";
      rev = "430a25393abbf482bddf03c224cd5b8eeb27b5e1";
      fetchSubmodules = false;
      sha256 = "sha256-0RvHUhfi/cn8rpGYf08oEhesLxTuMWHjZMlmpfzd17M=";
    };
  };
}
