# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  dav1d = {
    pname = "dav1d";
    version = "ebeaac6d60df0fdc8772f84d43a310eeed877185";
    src = fetchgit {
      url = "https://code.videolan.org/videolan/dav1d";
      rev = "ebeaac6d60df0fdc8772f84d43a310eeed877185";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qIFDldc7FiBgmQUNSwrNyDC0XBbNJI9ub9S868lnMno=";
    };
  };
  fuzzel = {
    pname = "fuzzel";
    version = "e661458d795e42733df2cb439d951bcde62fde8f";
    src = fetchgit {
      url = "https://codeberg.org/dnkl/fuzzel";
      rev = "e661458d795e42733df2cb439d951bcde62fde8f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-+eKA72LKfaktW0c3VMJSgjEW+DexrI6K3S4/LE7M8L8=";
    };
  };
  libplacebo = {
    pname = "libplacebo";
    version = "b4867541d4ba4fe7a2243d00a77d0bd348714bd8";
    src = fetchgit {
      url = "https://code.videolan.org/videolan/libplacebo/";
      rev = "b4867541d4ba4fe7a2243d00a77d0bd348714bd8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-m+4brYk+9Str0hKUik54UaFOrYFcaLF1yq8Bp9Ab388=";
    };
  };
  mpv = {
    pname = "mpv";
    version = "afe29026edcb3104cd64764f79fe8630e3d37242";
    src = fetchFromGitHub {
      owner = "mpv-player";
      repo = "mpv";
      rev = "afe29026edcb3104cd64764f79fe8630e3d37242";
      fetchSubmodules = false;
      sha256 = "sha256-ZoEFecJl6puSRCvMkkIr9XUl9iLFEF8Rh91r3uEHCWo=";
    };
  };
  spellsitter = {
    pname = "spellsitter";
    version = "f84e7a31c516f2a9cb857a02e4b551b009a81afb";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "spellsitter.nvim";
      rev = "f84e7a31c516f2a9cb857a02e4b551b009a81afb";
      fetchSubmodules = false;
      sha256 = "sha256-lYyTA9hvxljNy0n3xZCCwC1e+W1mBBwdGDKXiWY1x4E=";
    };
  };
}
