# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5438ecdd-72e9-4fbc-96ce-c116a8fff87d";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/153c78ff-6fa5-43d0-8d9a-f94a304f1e64";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/61d91e44-4c05-4201-bdec-ccc63a03ea9b";
    fsType = "ext4";
  };

  swapDevices = [];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
