# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  dav1d = {
    pname = "dav1d";
    version = "8ccdf0f6b91e43b589c195151ec3bffb3db417f1";
    src = fetchgit {
      url = "https://code.videolan.org/videolan/dav1d";
      rev = "8ccdf0f6b91e43b589c195151ec3bffb3db417f1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-eyerNV5nqL8BC/DT5J4TjTjpFaopTzjMubSGVV/DjnE=";
    };
  };
  fuzzel = {
    pname = "fuzzel";
    version = "8e09393463a00fd233b8d3b2ac316c2cfea6c791";
    src = fetchgit {
      url = "https://codeberg.org/dnkl/fuzzel";
      rev = "8e09393463a00fd233b8d3b2ac316c2cfea6c791";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-bSpUuRT9UaTJCftfkvJSba3Bt2PoeXRBkAqRnaqV08I=";
    };
  };
  libplacebo = {
    pname = "libplacebo";
    version = "08140178a8fe3fa8905ba0dd87b5231c4a59e607";
    src = fetchgit {
      url = "https://code.videolan.org/videolan/libplacebo/";
      rev = "08140178a8fe3fa8905ba0dd87b5231c4a59e607";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-N4Qrk+u+brgpNK4UQowGW7Kt5gSaDuHvJSzRXFIP2Hk=";
    };
  };
  mpv = {
    pname = "mpv";
    version = "bc9805c71a67b2717c79533731608eff679cded1";
    src = fetchFromGitHub ({
      owner = "mpv-player";
      repo = "mpv";
      rev = "bc9805c71a67b2717c79533731608eff679cded1";
      fetchSubmodules = false;
      sha256 = "sha256-m1UpIZDlMAeIBsPwKeSGIpsIFfE9hV24NhqafJ5qH3I=";
    });
  };
}
