# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
}: {
  dav1d = {
    pname = "dav1d";
    version = "11aa919a2f673b1d7ca338e4fbc5f5aa57805f44";
    src = fetchgit {
      url = "https://code.videolan.org/videolan/dav1d";
      rev = "11aa919a2f673b1d7ca338e4fbc5f5aa57805f44";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1019d3gfb7av2b1m9v9zf9v65bnhj01mw31d6jzziq1m5byr7mpc";
    };
  };
  fuzzel = {
    pname = "fuzzel";
    version = "d1ef3abd4feb75c6c54f137556e397e2462de78c";
    src = fetchgit {
      url = "https://codeberg.org/dnkl/fuzzel";
      rev = "d1ef3abd4feb75c6c54f137556e397e2462de78c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "07r4yy0csz026v780d346yvfdh0ll7a73zp1bskcd2br5lgj4hpa";
    };
  };
  libplacebo = {
    pname = "libplacebo";
    version = "f85c3c0791271089a3b1df2b5d6948cd1cb8c63e";
    src = fetchgit {
      url = "https://code.videolan.org/videolan/libplacebo/";
      rev = "f85c3c0791271089a3b1df2b5d6948cd1cb8c63e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1s02cq1b640npj942vivs7chl081lyg3mp92rj9laa9lyabi21d9";
    };
  };
  mpv = {
    pname = "mpv";
    version = "9d133eb00b541eecf828a03a7da1c9ec502287ba";
    src = fetchgit {
      url = "https://github.com/mpv-player/mpv";
      rev = "9d133eb00b541eecf828a03a7da1c9ec502287ba";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0fhy3977vi0zd0g56h0dad4d9rn5pz3r7f8pmyb04b0srvw3q33x";
    };
  };
}
