# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  dav1d = {
    pname = "dav1d";
    version = "1f09a9119fb794ab41b1e527d848c2a210ca43d4";
    src = fetchgit {
      url = "https://code.videolan.org/videolan/dav1d";
      rev = "1f09a9119fb794ab41b1e527d848c2a210ca43d4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-yMMj9TNCfODI0Wf064T5AR+LFuPsPso1I1q9z9A5SuE=";
    };
  };
  fuzzel = {
    pname = "fuzzel";
    version = "c703b99b9185d6e4bb04495abeb676a71e8fbe6f";
    src = fetchgit {
      url = "https://codeberg.org/dnkl/fuzzel";
      rev = "c703b99b9185d6e4bb04495abeb676a71e8fbe6f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-7A8AuAZKC1sb25T4ZvT3LCdpSIoV1CEWPLr/KCIbNIU=";
    };
  };
  libplacebo = {
    pname = "libplacebo";
    version = "aff39f522760376c7b532cde6a68560e5e987ff1";
    src = fetchgit {
      url = "https://code.videolan.org/videolan/libplacebo/";
      rev = "aff39f522760376c7b532cde6a68560e5e987ff1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-hciNlXKsshbYvcVNhl35xUTWMMExadzyqk5UhuVAXJQ=";
    };
  };
  mpv = {
    pname = "mpv";
    version = "c72b897e9cb60a3dd4a4fd35442ba21ea7ef6163";
    src = fetchFromGitHub ({
      owner = "mpv-player";
      repo = "mpv";
      rev = "c72b897e9cb60a3dd4a4fd35442ba21ea7ef6163";
      fetchSubmodules = false;
      sha256 = "sha256-nZg8j1oSxn+w9utxmgM+3qxBzHdtLD+YoIV2FVvTDBg=";
    });
  };
}
